---

- name: ethicalhackers.local workstation configuration
  hosts: win_workstation

  roles:
    - commonwkstn

  tasks:


  - name: Ensure that bob@ethicalhackers.local is present as local administrator
    win_group_membership:
      name: Administrators
      Members:
        - bob@ethicalhackers.local
      state: present

