- name: Test DNS
  ansible.windows.win_dns_client:
    adapter_names: '*'
    dns_servers: 8.8.8.8

- name: disable enhanced exit codes
  win_chocolatey_feature:
    name: useEnhancedExitCodes
    state: disabled

- name: Change the hostname to domain-controller
  win_hostname:
    name: domain-controller
  register: win_hostname

- name: Reboot
  win_reboot:
  when: win_hostname.reboot_required
  
- name: Ensure that Administrator is present with a valid password
  win_user:
    name: Administrator
    password: Mdp1234!
    password_never_expires: yes
    state: present
  ignore_errors: yes

- name: Ensure that ethicalhackers.local domain exixts
  win_domain:
    dns_domain_name: ethicalhackers.local
    safe_mode_password: Mdp1234!
  register: check_domain

- name: Reboot to complete ethicalhackers.local domain creation
  win_reboot:
  when: check_domain.changed

- name: Ensure the server is a domain controller
  win_domain_controller:
    dns_domain_name: ethicalhackers.local
    domain_admin_user: Administrator@ethicalhackers.local
    domain_admin_password: Mdp1234!
    safe_mode_password: Mdp1234!
    state: domain_controller
    log_path: C:\ansible_win_domain_controller.txt
  register: check_domain_controller


- name: Reboot to complete domain controller setup
  win_reboot:
  when: check_domain_controller.changed

- name: Check for xDnsServer Powershell module
  win_psmodule:
    name: xDnsServer
    state: present


- name: Ensure that admin@ethicalhackers.local is present as Domain Admin
  win_domain_user:
    name: admin
    password: Mdp1234!
    password_never_expires: yes
    state: present
    path: cn=Users,dc=ethicalhackers,dc=local
    groups:
      - Domain Admins

- name: Ensure that bob@ethicalhackers.local is present in OU cn=Users,dc=ethicalhackers,dc=local
  win_domain_user:
    name: bob
    password: Mdp1234!
    password_never_expires: yes
    state: present
    path: cn=Users,dc=ethicalhackers,dc=local
    groups:
      - Users

- name: Ensure that alice@ethicalhackers.local is present in OU cn=Users,dc=ethicalhackers,dc=local
  win_domain_user:
    name: alice
    password: Mdp1234!
    password_never_expires: yes
    state: present
    path: cn=Users,dc=ethicalhackers,dc=local
    groups:
      - Users

- name: Create AllTeams group
  win_domain_group:
    name: allTeams
    scope: global
    path: DC=ethicalhackers,DC=local
    state: present

- name: Create DBAOracle
  win_domain_group:
    name: DBAOracle
    scope: global
    path: DC=ethicalhackers,DC=local
    state: present

- name: Create DBASQLServer
  win_domain_group:
    name: DBASQLServer
    scope: global
    path: DC=ethicalhackers,DC=local
    state: present

- name: Create DBAMongo group
  win_domain_group:
    name: DBAMongo
    scope: global
    path: DC=ethicalhackers,DC=local
    state: present

- name: Create DBARedis group
  win_domain_group:
    name: DBARedis
    scope: global
    path: DC=ethicalhackers,DC=local
    state: present

- name: Create DBAEnterprise Group ...
  win_domain_group:
    name: DBAEnterprise
    scope: global
    path: DC=ethicalhackers,DC=local
    state: present

- name: Create a Test Group ...
  win_domain_group:
    name: JustATestDemo
    scope: global
    path: DC=ethicalhackers,DC=local
    state: present
