
- name: Configure dns
  tags: dns
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - "{{ dc_ip }}"
    log_path: C:\dns_log.txt

- name: Ensure directory structure for public share exists
  win_file:
    path: C:\shares\public
    state: directory

- name: Ensure public share exists
  win_share:
    name: public
    description: Basic RW share for all domain users
    path: C:\shares\public
    list: yes
    full: Administrators
    change: Users

- name: add windows 10 workstation to ethicalhackers.local
  win_domain_membership:
    dns_domain_name: ethicalhackers.local
    domain_admin_user: Administrator@ethicalhackers.local
    domain_admin_password: "{{ Administrator_pass }}"
    state: domain
  register: domain_state


- name: Change the hostname to win-workstation-1
  win_hostname:
    name: win-workstation-1
  register: res

- name: Reboot
  # In case it stucks here saying "A system shutdown was in progress", reboot manually the vm and launch the playbook again
  win_reboot:
    reboot_timeout: 2000
  when: res.reboot_required

